### ISSUE TITLE
Create Column Feature Metrics

### ISSUE THREAD

**Issue by banjtheman** [banjtheman/fancylit#13]
# What is the Task
Create a function that can render a metrics from a column in dataframe

## Why do we want to do this
To provide an easy way to show high level metrics

## How can I get started?
1. Create a new function in [data_stats.py](https://github.com/banjtheman/fancylit/blob/main/fancylit/stats/data_stats.py) called `show_metrics` that takes in a data frame as a parameter/

2. Have a drop-down select a column from the dataframe and create the following metrics for a column, 
* mean
* max
* min
* std
* count

Create 5 st.columns with and use st.metric to show the data

Example code here:  https://docs.streamlit.io/en/stable/api.html#streamlit.metric

3. Export the module in `__init__.py`
https://github.com/banjtheman/fancylit/blob/main/fancylit/stats/__init__.py

4. Add the show_metrics function to `example_app.py` 

## Definition of Done
Show Metrics is rendered in example_app.py

**Comment by DireWolf707** [comment]
Please check if it is the desired result

[![0c4b0d03e13b9429cd430e5ea4ad2ac0c510ebdd.gif](https://s9.gifyu.com/images/0c4b0d03e13b9429cd430e5ea4ad2ac0c510ebdd.gif)](https://gifyu.com/image/Pw9f)

**Comment by banjtheman** [comment]
Yea looks good

**Comment by DireWolf707** [comment]
I have added a PR for hacktoberfest. Please check if changes align with the project structure and needs as I am willing to contribute on more issues in this project, will start working on them after your approval on this one.

**Comment by banjtheman** [comment]
> 
> 
> I have added a PR for hacktoberfest. Please check if changes align with the project structure and needs as I am willing to contribute on more issues in this project, will start working on them after your approval on this one.

Thank you, feel free to pick up another issue
