### ISSUE TITLE
Create Interactive HeatMap function

### ISSUE THREAD

**Issue by banjtheman** [banjtheman/fancylit#2]
# What is the Task
Create a function that can render an interactive heat map from a dataframe

## Why do we want to do this
To provide an easy way to show a Heat Map

## How can I get started?
1. Create a new function in [charts.py](https://github.com/banjtheman/fancylit/blob/main/fancylit/viz/charts.py) called `heat_map` that takes in a dataframe as a parameter 
2. Have the function provide selectable widgets for the graph axes like this https://github.com/banjtheman/fancylit/blob/main/fancylit/viz/charts.py#L18-L23

3. Render a Heat Map with Altair with the selected values, Example code:
https://altair-viz.github.io/gallery/simple_heatmap.html

4. Export the module in `__init__.py`
https://github.com/banjtheman/fancylit/blob/main/fancylit/viz/__init__.py

5. Add the heat_map function to `example_app.py` 
https://github.com/banjtheman/fancylit/blob/main/example_app.py#L23

## Definition of Done
Heat map is rendered in example_app.py

**Comment by rubyruins** [comment]
Hey @banjtheman, could I work on this for Hacktoberfest?
