### ISSUE TITLE
Create Interactive Scatter Plot function

### ISSUE THREAD

**Issue by banjtheman** [banjtheman/fancylit#3]
# What is the Task
Create a function that can render an interactive scatter plot from a dataframe

## Why do we want to do this
To provide an easy way to show a Scatter Plot

## How can I get started?
1. Create a new function in [charts.py](https://github.com/banjtheman/fancylit/blob/main/fancylit/viz/charts.py) called `scatter_plot` that takes in a dataframe as a parameter 
2. Have the function provide selectable widgets for the graph axises like this https://github.com/banjtheman/fancylit/blob/main/fancylit/viz/charts.py#L18-L23

3. Render a Scatter plot with Altair with the selected values, Example code:
https://altair-viz.github.io/gallery/simple_line_chart.html

4. Export the module in `__init__.py`
https://github.com/banjtheman/fancylit/blob/main/fancylit/viz/__init__.py

5. Add the scatter_plot function to `example_app.py` 
https://github.com/banjtheman/fancylit/blob/main/example_app.py#L23

## Definition of Done
Scatter Plot is rendered in example_app.py

**Comment by nat236919** [comment]
Let me try to work on this issue

**Comment by banjtheman** [comment]
closed by #19
