### ISSUE TITLE
Create Interactive 3d Plot Function

### ISSUE THREAD

**Issue by banjtheman** [banjtheman/fancylit#5]
# What is the Task
Create a function that can render an interactive 3d Plot from a dataframe

## Why do we want to do this
To provide an easy way to show a 3d Plot

## How can I get started?
1. Create a new function in [charts.py](https://github.com/banjtheman/fancylit/blob/main/fancylit/viz/charts.py) called `three_d_plot` that takes in a dataframe as a parameter 
2. Have the function provide selectable widgets for the graph axes like this https://github.com/banjtheman/fancylit/blob/main/fancylit/viz/charts.py#L18-L23

3. Render a 3d Plot with Altair with the selected values, Example code:
https://plotly.com/python/3d-scatter-plots/

4. Export the module in `__init__.py`
https://github.com/banjtheman/fancylit/blob/main/fancylit/viz/__init__.py

5. Add the  3d Plot function to `example_app.py` 
https://github.com/banjtheman/fancylit/blob/main/example_app.py#L23

## Definition of Done
 3d Plot is rendered in example_app.py

**Comment by pedrogengo** [comment]
Hey, I would like to get this issue :)

**Comment by pedrogengo** [comment]
Done :) If you can validate and link, it will be fine!

**Comment by banjtheman** [comment]
closed by #17
