### ISSUE TITLE
Create Word Cloud from Column 

### ISSUE THREAD

**Issue by banjtheman** [banjtheman/fancylit#7]
# What is the Task
Create a function that can render a wordcloud from a column in dataframe

## Why do we want to do this
To provide an easy way to show a word cloud

## How can I get started?
1. Create a new function in [data_stats.py](https://github.com/banjtheman/fancylit/blob/main/fancylit/stats/data_stats.py) called `gen_wordcloud` that takes in a data frame as a parameter/

2. Have a drop-down select a column from the dataframe and create a wordcloud, here is example code
https://github.com/amueller/word_cloud/blob/master/examples/simple.py

3. Export the module in `__init__.py`
https://github.com/banjtheman/fancylit/blob/main/fancylit/stats/__init__.py

4. Add the gen_wordcloud function to `example_app.py` 

## Definition of Done
Word cloud is rendered in example_app.py

**Comment by DireWolf707** [comment]
Please check if it is the desired result
[![bandicam-2021-09-20-17-06-04-407.jpg](https://s9.gifyu.com/images/bandicam-2021-09-20-17-06-04-407.jpg)](https://gifyu.com/image/PvRG)

**Comment by DireWolf707** [comment]
Added PR for this feature. Kindly review and suggest changes ,if any.
Output:
[![bandicam-2021-09-20-17-06-04-407.jpg](https://s9.gifyu.com/images/bandicam-2021-09-20-17-06-04-407.jpg)](https://gifyu.com/image/PvRG)
