### ISSUE TITLE
Create a Feature Correlation Graph Function

### ISSUE THREAD

**Issue by banjtheman** [banjtheman/fancylit#9]
# What is the Task
Create a function that can render a Feature Correlation graph from a dataframe

## Why do we want to do this
To provide an easy way to show a Feature Correlation graph

## How can I get started?
1. Create a new function in [yellowbrick_funcs.py](https://github.com/banjtheman/fancylit/blob/main/fancylit/modeling/yellowbrick_funcs.py) called `feature_correlation` that takes in a dataframe as a parameter 

2. Leverage the data_prep function to get the dataframe ready https://github.com/banjtheman/fancylit/blob/main/fancylit/modeling/yellowbrick_funcs.py#L11

3. Render a Feature Correlation graph example code:
https://www.scikit-yb.org/en/latest/api/target/feature_correlation.html?highlight=FeatureCorrelation#mutual-information-regression

4. Export the module in `__init__.py`
https://github.com/banjtheman/fancylit/blob/main/fancylit/modeling/__init__.py

5. Add the  Feature Correlation plot to `example_app.py` 
https://github.com/banjtheman/fancylit/blob/main/example_app.py#L23

## Definition of Done
Feature Correlation is rendered in example_app.py

**Comment by pedrogengo** [comment]
Hey, I would like to get it!

**Comment by banjtheman** [comment]
closed by #22
